server:
  port: 8000

spring:
  application:
    name: cloud-service-center
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8000/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
#    enable-self-preservation: false # 自我保护模式 true 打开 默认true,false 关闭
security:
  basic:
    enabled: false
management:
  security:
    enabled: false