server:
  port: 1988
spring:
#  profiles: host1
  application:
    name: cloud-service-center
eureka:
  instance:
      hostname: host1
      prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1988/eureka/


#---
#
#server:
#  port: 1987
#spring:
#  profiles: host2
#  application:
#    name: cloud-service-center
#eureka:
#  instance:
#      hostname: host2
#      prefer-ip-address: true
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://host2:1988/eureka/