server:
  port: 1988
spring:
  application:
    name: cloud-service-center
eureka:
  instance:
      prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://localhost:${server.port}/eureka/
#  server:
#    enableSelfPreservation: false

